// Attempts to insert a list of endpoints into a readme between ### Begin autogeneration and ### End autogeneration
var fs = require('fs')
//arg 2 = temp file on your machine. $(mktemp) ofr macos. arg3=file you want to exeute this on
const outputFile = process.argv[2];
const endpointsFiles = [process.argv[3]];

const info = { info: { ...require('./../../package.json') } }
const settings = { replacementKeys: ['### Begin autogeneration', '### End autogeneration'] };
(async () => {
    var autoGeneratedDocs = await require('swagger-autogen')()(outputFile, endpointsFiles, info)
        .then(x => require('widdershins').convert(x.data, { headings: 0, language_tabs: [], language_clients: [] }))
    var readme = fs.readFileSync('readme.md', 'utf8')
    if (!readme.includes(settings.replacementKeys[1]) || !readme.includes(settings.replacementKeys[0])) throw "replacement keys not found";
    var p1 = readme.split(settings.replacementKeys[0])
    var p2 = p1[1].split(settings.replacementKeys[1])
    var insert = `${p1[0].trim()}
${settings.replacementKeys[0]}
${autoGeneratedDocs}
${settings.replacementKeys[1]}
${p2[1]}`;
    console.log("Writing updated readme.md...")
    fs.writeFileSync('readme.md', insert, { encoding: 'utf8', flag: 'w' })
    console.log("Writing completed for readme.md")
})()